# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
AGENT: incubation-lite
DEV_BUCKET: das-dev-applications-eu-west-1-de20
PROD_BUCKET: das-prod-applications-eu-west-1-de20
PROJECT_DIR: copier-project-example
PROJECT_GIT_URL: github.com/bugra-yilmaz/copier-project-example.git
STAGING_BUCKET: das-dev-applications-eu-west-1-de20
SVC_CORTEX_CREDENTIALS: 54b31b56-a912-11ec-b909-0242ac120002
USE_PYSPARK: true
WARNING_THIS_IS_TEMPLATED: '#===================================================================================

  # THIS IS A TEMPLATED FILE; NEVER EDIT MANUALLY

  #

  # These configurations should not be modified here, they are handled by the Copier

  # tool and the DICE template. If you need to change any implementation in this file,

  # please consider if they are generic enough to be included in the template, or

  # use a project specific file for your needs. Instructions can be found in:

  # https://tools.adidas-group.com/bitbucket/projects/CG/repos/daa_eds_python_template

  #===================================================================================

  '
_commit: 0.0.1
_src_path: git@github.com:bugra-yilmaz/copier-template-example.git
